# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Brancher
      run: cd brancher; go build -v ./...

    - name: Build CLI
      run: cd cli; go build -v ./...

    - name: Build DNS
      run: cd dns; go build -v ./...

    - name: Build Kubernator
      run: cd kubernator; go build -v ./...

#    - name: Test
#      run: go test -v ./...
